trigger:
- main
- beta

pool:
  vmImage: windows-latest

steps:
- task: UseNode@1
  inputs:
    version: '20.x'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: "Install NPM Dependencies"

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: "Build"

- script: 'npx semantic-release'
  displayName: 'Semantic Release'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    NPM_TOKEN: $(NPM_TOKEN)
